#!/bin/bash
set -euo pipefail
shopt -s nullglob

USER_LIB="$HOME/Music/Ableton/User Library/Presets/MIDI Effects/Max MIDI Effect"

cp "$USER_LIB"/Mega\ Drive\ FM* plugins/
cp "$USER_LIB"/MD_MIDI_CC_*.maxpat plugins/
